services:
  foxogram-api:
    build:
      context: ./foxogram-api
    restart: always
    ports:
      - '8080:8080'
    networks:
      - db_network
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`api.foxogram.su`)
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certresolver=letsencrypt
      - traefik.http.routers.foxogram-web.certresolver=letsencrypt

networks:
  db_network:
    external: true
  traefik:
    external: true
