services:
  foxogram-api-dev:
    build:
      context: ./foxogram-api
    restart: always
    ports:
      - '8090:8090'
    networks:
      - db_dev_network
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.apidev.rule=Host(`api.dev.foxogram.su`)
      - traefik.http.routers.apidev.tls=true
      - traefik.http.routers.apidev.tls.certresolver=letsencrypt
      - traefik.http.routers.foxogram-web.certresolver=letsencrypt

networks:
  db_dev_network:
    external: true
