name: Deploy Foxogram

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - run: |
          echo >> foxogram-common/src/resources/application.yml << EOF
          spring:
            datasource:
              driver-class-name: org.postgresql.Driver
              username: ${{ secrets.DB_USERNAME }}
              password: ${{ secrets.DB_PASSWORD }}
              url: jdbc:postgresql://foxogram-db:5432/postgres
          jpa:
            hibernate:
              ddl-auto: update
        
          smtp:
            host: ${{ secrets.SMTP_HOSTNAME }}
            port: 587
            username: ${{ secrets.SMTP_USERNAME }}
            password: ${{ secrets.SMTP_PASSWORD }}
            email: noreply@foxogram.su
          
          jwt:
            secret: ${{ secrets.JWT_SECRET }}
          
          api:
            version: 1
          EOF

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build Foxogram API
        run: ./gradlew :foxogram-api:build

      - name: Run Foxogram API
        run: docker compose up -d
